language: node_js
sudo: false

env:
  - TEST_DIVA=source
  - TEST_DIVA=build

install:
  - npm install -g gulp
  - npm install

script: gulp develop:test

notifications:
webhooks:
    urls:
      - https://webhooks.gitter.im/e/6885fd1dbe70aca78516
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always